---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: terraform action
description: an action used for plan and apply the configuration in Terraform cloud
inputs:  
  workspace-id:
    description: the id of the workspace
    required: true
  token:
    description: the token used for connecting Terraform Cloud
    required: true
  auto-apply:
    description: whether apply automatically when plan succeeded
    required: false
    default: true
runs:
  using: composite
  steps:
    - id: plan
      name: run
      uses: docker://finalspy/busybox-curl-jq:latest
      shell: sh
      run: |

        #!/bin/bash

        PAYLOAD=$(cat <<EOF
          {
          "data": {
            "attributes": {
            "auto-apply": "${{ inputs.auto-apply }}",
            "message": "Triggered run via curl"
            },
          "type": "runs",
          "relationships": {
            "workspace": {
              "data": {
                "type": "workspaces",
                "id": "${{ inputs.workspace-id }}"
              }
            }
          }
         }
        }
EOF
        )
        
        echo $PAYLOAD

        curl -s -X POST "https://app.terraform.io/api/v2/runs" -H "Authorization: Bearer ${{ inputs.token }}" -H "Content-Type: application/vnd.api+json" --data "$PAYLOAD"
